name: CD

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  staging_deployment:
    name: BillManager Staging Deployment
    environment: staging
    defaults:
      run:
        shell: bash
        working-directory: '.'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Configure envs
        run: |
          touch $GITHUB_WORKSPACE/.env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> $GITHUB_WORKSPACE/.env

      - name: Starting Project
        run: npm install

      - name: deploy project in staging
        run: npm run deploy:staging
